### ISSUE TITLE
可否分享相关的参考资料呢？

### ISSUE THREAD

**Issue by Wings236** [datawhalechina/hugging-rl#1]
想知道，你们有按照什么相关资料来梳理这一块的内容的

**Comment by Evan-wyl** [comment]
> 想知道，你们有按照什么相关资料来梳理这一块的内容的

之前是基于综述论文，当下是基于作者们学习过程中遇到的经典算法，然后梳理出来。

**Comment by Wings236** [comment]
所以，现在是边梳理边找相关的文献是吗？

**Comment by Evan-wyl** [comment]
> 所以，现在是边梳理边找相关的文献是吗？

是的
